### ISSUE TITLE
ednc-dismiss-notification  key binding not working for me

### ISSUE THREAD

**Issue by NapoleonWils0n** [sinic/ednc#5] opened 2022-11-25 00:38 UTC
Hi Mate

I cant seem to get the ednc-dismiss-notification  key binding working in the ednc-log
right clicking the notification does dismiss it but pressing d doesnt work

i did see this part of the read me
"By default, you can use the following mouse controls and key bindings (the latter only in the log buffer):"

the tab works to expand the notification in the log view

when i run M-x ednc-
i can see all the commands but only ednc-toggle-expanded-view has the tab keybinding listed

im running emacs 29, 
i was wondering if maybe thats causing the issue with the keybindings

I just switched from gnome's notification center to using ednc and made a video about it,
hope i covered everything properly and didnt miss anything 

[Emacs Desktop Notification Center youtube](https://www.youtube.com/watch?v=StbSdYcLucEl)

**Comment by sinic** [comment] 2022-11-25 17:21
Sorry, can't reproduce the issue. It works for me both on Debian's Emacs 27.1, as well as on a freshly compiled Emacs 29.0.50. Maybe you have some other (possibly global) minor mode interfering? Does `describe-mode` in `*ednc-log*` report the binding?

> [Emacs Desktop Notification Center youtube](https://www.youtube.com/watch?v=StbSdYcLucEl)

Cool, thanks for helping to get the word out!

I'll open separate issues for points mentioned in the video, but there are subtle reasons for many of them, so fixes won't be straightforward, unfortunately.

**Comment by NapoleonWils0n** [comment] 2022-11-25 19:39
Running describe-mode in the *ednc-log* outputs this:

Minor modes enabled in this buffer: Company Evil-Collection-Unimpaired Evil-Local Font-Lock Undo-Tree

and these are the listed keybiindings

`
TAB		ednc-toggle-expanded-view
RET		ednc-invoke-action
SPC		scroll-up-command
-		negative-argument
1 .. 9		digit-argument
<		beginning-of-buffer
>		end-of-buffer
d		ednc-dismiss-notification
q		quit-window
DEL		scroll-down-command
S-SPC		scroll-down-command
`


i think your right its probably another mode like evil being evil :)

ill have to figure out how to disable the other modes in ednc-mode,
time to have bit of a google

hope you dont mind the suggestions in the video, 
im sure everything is done a certain way for a  good reason

i run emacs 29 as a gtk wayland app on gnome and ednc works like a charm,
there arent many options if you want to replace the built in gnome notifications

I made some notes and a video about how to disable gnome notifications,
i dont know if thats any use for your documentation 
if you want to explain to people running gnome how to easily switch to using ednc

and also some of the advantages ednc has over gnome notifications 
like the fact that gnome notifications are collapsed in the notification view 
and you cant actually read the message, whereas ednc has log of all notifications

disable gnome notifications notes

[disable gnome notifications - how to](https://github.com/NapoleonWils0n/cerberus/blob/master/ubuntu/nognome_notifications_setup/nognome_notifications.org)

[disable gnome notifications - youtube](https://www.youtube.com/watch?v=4nB_ChYQK8c)


if you need a Guinea pig to test anything id more than happy to help,
my shell scripting is fine but my lisp is rather like my french very limited

**Comment by NapoleonWils0n** [comment] 2022-11-26 01:40
i used add-hook with  'ednc-view-mode-hook and evil-define-key to fix the issue

`
;; ednc evil - normal mode
(defun noevil ()
  (evil-define-key 'normal ednc-view-mode-map "d" 'ednc-dismiss-notification)
)

(add-hook 'ednc-view-mode-hook 'noevil)

`

**Comment by sinic** [comment] 2022-11-26 12:35
> i used add-hook with 'ednc-view-mode-hook and evil-define-key to fix the issue

Great, so I'm closing this issue as resolved; I don't think EDNC could do anything different here.

> hope you dont mind the suggestions in the video,

Not at all.

**Closed as completed by sinic** 2022-11-26 12:35 UTC
